export const ADD_ITEM: 'ADD_ITEM' = 'ADD_ITEM';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const DELETE_ITEM: 'DELETE_ITEM' = 'DELETE_ITEM';
export const SORT_ITEMS: 'SORT_ITEMS' = 'SORT_ITEMS';
export const RESET_CONSTRUCTOR: 'RESET_CONSTRUCTOR' = 'RESET_CONSTRUCTOR';
